# Generated by Django 4.0.6 on 2022-10-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profiles_short_intro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='social_youtube',
            new_name='social_stackoverflow',
        ),
        migrations.AddField(
            model_name='profiles',
            name='social_twitter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
