# Generated by Django 4.0.6 on 2022-09-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tag_projects_vote_ratio_projects_vote_total_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='tags',
            field=models.ManyToManyField(blank=True, to='projects.tag'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='value',
            field=models.CharField(choices=[('Up', 'Up Vote'), ('Down', 'Down Vote')], max_length=200, verbose_name='vote Up/Down'),
        ),
    ]
