# Generated by Django 4.0.6 on 2022-09-29 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New',
        ),
    ]
