# Generated by Django 4.0.6 on 2022-09-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_delete_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='vote_ratio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='vote_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
