# Generated by Django 4.0.6 on 2022-11-15 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_social_youtube_profiles_social_stackoverflow_and_more'),
        ('projects', '0008_projects_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='reviews',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profiles'),
        ),
        migrations.AlterUniqueTogether(
            name='reviews',
            unique_together={('owner', 'projects')},
        ),
    ]
